/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 javascript.glb 
Author: titopetri (https://sketchfab.com/titopetri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/logotipos-3d-aprenda-programar-562ee24508584bb889e1ff12e656abe5
Title: Logotipos 3D - Aprenda Programar
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/javascript.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.864, -0.5, 0]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.JAVASCRIPT} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.BORDAS_CROMADO} />
      </group>
    </group>
  )
}

useGLTF.preload('/javascript.glb')
